client/src/main/java/com/sap/mobile/services/client/push/LocalizedBulkPush.java, client/src/main/java/com/sap/mobile/services/client/push/LocalizedPushPayload.java, client/src/main/java/com/sap/mobile/services/client/push/LocalizedUserNotification.java, client/src/main/java/com/sap/mobile/services/client/push/NotificationStatus.java, client/src/main/java/com/sap/mobile/services/client/push/PushResult.java
Add missing docs and fix minor formatting issue with status code list
=> Document Push Service Localized Notifications

client/src/main/java/com/sap/mobile/services/client/push/BaiduMsgType.java, client/src/main/java/com/sap/mobile/services/client/push/BaiduNotification.java, client/src/main/java/com/sap/mobile/services/client/push/DTO.java, client/src/main/java/com/sap/mobile/services/client/push/PushRegistration.java
=> Add Missing Baidu msgType Property

client/pom.xml, pom.xml, samples/cloud-foundry-binding-sample/pom.xml, samples/pom.xml, validation/mobile-service-broker/pom.xml, validation/pom.xml, validation/system-tests/pom.xml
@DirkG68 Let's do a patch release of version `0.2.0` -> `0.2.1` to update the FOSS dependencies.
=> Prepare version for patch release 0.2.1

client/pom.xml, pom.xml, samples/cloud-foundry-binding-sample/pom.xml, samples/pom.xml, validation/mobile-service-broker/pom.xml, validation/pom.xml, validation/system-tests/pom.xml
Let's do a patch release of version 0.2.1 -> 0.2.2 to update the FOSS dependencies.
=> Prepare version for patch release 0.2.2

pom.xml
Maven Central staging profile id has changed
=> update oss staging profile id

client/pom.xml, client/src/main/java/com/sap/mobile/services/client/ClientErrorException.java, client/src/main/java/com/sap/mobile/services/client/ClientException.java, client/src/main/java/com/sap/mobile/services/client/ClientUnauthorizedException.java, client/src/main/java/com/sap/mobile/services/client/HttpHeaders.java, client/src/main/java/com/sap/mobile/services/client/RestTemplateResponseErrorHandler.java, client/src/main/java/com/sap/mobile/services/client/ServerErrorException.java, client/src/main/java/com/sap/mobile/services/client/TrialLimitExceededException.java, client/src/main/java/com/sap/mobile/services/client/push/MessageErrorException.java, client/src/main/java/com/sap/mobile/services/client/push/NoMessageSentException.java, client/src/main/java/com/sap/mobile/services/client/push/PushClientException.java, client/src/main/java/com/sap/mobile/services/client/push/PushRestTemplateResponseErrorHandler.java, client/src/test/java/com/sap/mobile/services/client/push/PushClientMockedTest.java
Enhanced Client Exception now contain:
- (log) correlationId
- service response body
- response headers
Push Client throws PushClientException with PushResponse property.
=> Improved Client Error Handling

.github/workflows/build.yaml, .github/workflows/bump-version.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/perform-release.yaml, .github/workflows/pr-voter.yaml, .github/workflows/prepare-patch-release.yaml, .github/workflows/release-documentation.yaml, .github/workflows/trigger-release.yaml, client/pom.xml, client/src/main/java/com/sap/mobile/services/client/RestTemplateResponseErrorHandler.java, client/src/main/java/com/sap/mobile/services/client/XsuaaAuthorizationRequestInterceptor.java, client/src/main/java/com/sap/mobile/services/client/push/BaiduNotification.java, client/src/main/java/com/sap/mobile/services/client/push/PushRestTemplateResponseErrorHandler.java, client/src/test/java/com/sap/mobile/services/client/MobileServicesSettingsTest.java, client/src/test/java/com/sap/mobile/services/client/ServiceKeyClientConfigurationTest.java, client/src/test/java/com/sap/mobile/services/client/XsuaaAuthorizationRequestInterceptorTest.java, client/src/test/java/com/sap/mobile/services/client/XsuaaClientConfigurationTest.java, pom.xml, samples/cloud-foundry-binding-sample/pom.xml, validation/mobile-service-broker/README.md, validation/mobile-service-broker/pom.xml, validation/mobile-service-broker/src/main/java/com/sap/mobile/services/client/validation/broker/misc/OAuthTokenProvider.java, validation/mobile-service-broker/src/main/java/com/sap/mobile/services/client/validation/broker/service/CredentialStoreClient.java, validation/system-tests/pom.xml
This pull request upgrades the Spring Libraries to Spring Boot 3 and Spring Framework 6. This also lifts the minimum required Java version to 17.
As of now, we cannot upgrade CF related libraries due to a missing Java Build Pack for JDK 17 /Spring Boot 3
=> Spring Boot 3 Version Support

client/pom.xml, client/src/main/java/com/sap/mobile/services/client/XsuaaAuthorizationRequestInterceptor.java
Also reverting change needed because status code
property getter was accidentially removed from exception.
=> Bump com.sa.cloud.security.xsuaa to 3.1.2

README.md
... and Spring Boot reference.
=> Document Minimum Required JDK Version

client/src/main/java/com/sap/mobile/services/client/push/PushPayload.java, client/src/test/java/com/sap/mobile/services/client/push/PushClientTest.java
Add data map builder to PushPayload.
=> Helper for PushPayload.data Added

.github/actions/packages/prepare-mobile-services-app/package-lock.json
Reverts SAP/java-integration-for-sap-mobile-services#460
=> Revert "Bump got from 14.2.1 to 14.3.0 in /.github/actions"

.github/actions/packages/prepare-mobile-services-app/package-lock.json, .github/actions/packages/prepare-mobile-services-app/package.json
Reverts SAP/java-integration-for-sap-mobile-services#459
=> Revert "Bump @sap/xssec from 3.6.1 to 4.0.0 in /.github/actions"

.github/actions/packages/prepare-mobile-services-app/package-lock.json, .github/actions/packages/prepare-mobile-services-app/package.json
Reverts SAP/java-integration-for-sap-mobile-services#464 after fixing tar version
=> Revert "Revert "Bump @sap/xssec from 3.6.1 to 4.0.0 in /.github/actions""

.github/actions/packages/prepare-mobile-services-app/package-lock.json
Reverts SAP/java-integration-for-sap-mobile-services#463 after fixed library version
=> Revert "Revert "Bump got from 14.2.1 to 14.3.0 in /.github/actions""

.github/actions/packages/prepare-mobile-services-app/package.json
Downgrade to latest working version
=> Downgrade sap/xssec to 3.6.1

.github/actions/package-lock.json, .github/actions/packages/prepare-mobile-services-app/client.js, .github/actions/packages/prepare-mobile-services-app/package.json
Migrate the `sap/xssec` library used in gh-actions to `v4`
=> Upgrade sap/xssec library to v4

validation/mobile-service-broker/README.md
Minor internal doc enhancement reflecting behavior on expired X509 keys
=> Add Error Hint on Expired Keys

client/src/main/java/com/sap/mobile/services/client/push/Constants.java, client/src/main/java/com/sap/mobile/services/client/push/DTO.java, client/src/main/java/com/sap/mobile/services/client/push/PushClient.java, client/src/main/java/com/sap/mobile/services/client/push/PushRegistrationsResponse.java, client/src/main/java/com/sap/mobile/services/client/push/RestTemplatePushClient.java, client/src/test/java/com/sap/mobile/services/client/push/DTOTest.java, client/src/test/resources/payloads/response-get-registrations-with-single-registration.json
Ensure both methods are working.
Issue: #515
=> Fix Issue 515: getRegistrations/getRegistration

.github/workflows/build.yaml, .github/workflows/bump-version.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/perform-release.yaml, .github/workflows/pr-voter.yaml, .github/workflows/prepare-patch-release.yaml, .github/workflows/release-documentation.yaml, .github/workflows/trigger-release.yaml
Hi Colleagues,
[SapMachine](https://sapmachine.io/) is now available with
actions/setup-java@v4
Created a PR to migrate from Temurin 17 to SapMachine 17
Regards Christian@SapMachine Team
=> chore: Migrate from Temurin 17 to SapMachine 17

.github/workflows/build.yaml
This action reports a conflict/existing package. In order to update the development build, an unique is added
=> Fix Javadoc Artifact Upload

.github/workflows/build.yaml
Reverts SAP/java-integration-for-sap-mobile-services#559
=> Revert "Remove Java Doc Upload Artifact Step"
